// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JwtDtoProto.proto

package ru.clevertec.news.model.dto;

public interface JwtDtoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ru.clevertec.news.model.dto.JwtDto)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string access_token = 1;</code>
     *
     * @return The accessToken.
     */
    java.lang.String getAccessToken();

    /**
     * <code>string access_token = 1;</code>
     *
     * @return The bytes for accessToken.
     */
    com.google.protobuf.ByteString
    getAccessTokenBytes();
}
