// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JwtDtoProto.proto

package ru.clevertec.news.model.dto;

public final class JwtDtoProto {
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_ru_clevertec_news_model_dto_JwtDto_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_ru_clevertec_news_model_dto_JwtDto_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021JwtDtoProto.proto\022\033ru.clevertec.news.m" +
                        "odel.dto\"\036\n\006JwtDto\022\024\n\014access_token\030\001 \001(\t" +
                        "B\002P\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_ru_clevertec_news_model_dto_JwtDto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_ru_clevertec_news_model_dto_JwtDto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_ru_clevertec_news_model_dto_JwtDto_descriptor,
                new java.lang.String[]{"AccessToken",});
    }

    private JwtDtoProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    // @@protoc_insertion_point(outer_class_scope)
}
