// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignUpDtoProto.proto

package ru.clevertec.news.model.dto;

/**
 * Protobuf enum {@code ru.clevertec.news.model.dto.RoleName}
 */
public enum RoleName
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ADMIN = 0;</code>
   */
  ADMIN(0),
  /**
   * <code>JOURNALIST = 1;</code>
   */
  JOURNALIST(1),
  /**
   * <code>SUBSCRIBER = 2;</code>
   */
  SUBSCRIBER(2),
  /**
   * <code>USER = 3;</code>
   */
  USER(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ADMIN = 0;</code>
   */
  public static final int ADMIN_VALUE = 0;
  /**
   * <code>JOURNALIST = 1;</code>
   */
  public static final int JOURNALIST_VALUE = 1;
  /**
   * <code>SUBSCRIBER = 2;</code>
   */
  public static final int SUBSCRIBER_VALUE = 2;
  /**
   * <code>USER = 3;</code>
   */
  public static final int USER_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RoleName valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static RoleName forNumber(int value) {
    switch (value) {
      case 0: return ADMIN;
      case 1: return JOURNALIST;
      case 2: return SUBSCRIBER;
      case 3: return USER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RoleName>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RoleName> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RoleName>() {
          public RoleName findValueByNumber(int number) {
            return RoleName.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ru.clevertec.news.model.dto.SignUpDtoProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final RoleName[] VALUES = values();

  public static RoleName valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RoleName(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ru.clevertec.news.model.dto.RoleName)
}

