// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignInDtoProto.proto

package ru.clevertec.news.model.dto;

public final class SignInDtoProto {
  private SignInDtoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_clevertec_news_model_dto_SignInDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_clevertec_news_model_dto_SignInDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SignInDtoProto.proto\022\033ru.clevertec.new" +
      "s.model.dto\",\n\tSignInDto\022\r\n\005login\030\001 \001(\t\022" +
      "\020\n\010password\030\002 \001(\tB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ru_clevertec_news_model_dto_SignInDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_clevertec_news_model_dto_SignInDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_clevertec_news_model_dto_SignInDto_descriptor,
        new java.lang.String[] { "Login", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
